import "@/app/globals.css";
import MessageButton from "@/components/Button";
import { getCounter } from "@/utils/requests";
import styles from "@/styles/promo.module.scss";
import Image from "next/image";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PromoPage() {
  const counter = Promise.resolve(getCounter());
  return (
    <>
      <header className={styles.header}>
        <Image
          src="/logo_amz.png"
          className={styles.img_pizza}
          width={150}
          height={75}
          alt="pizza"
        />
      </header>
      <main className={styles.promoPage}>
        <h1>Promoção</h1>
        <h2>Pizza Gigante + Guaraná Kuat 2L</h2>
        <div className={styles.banner}>
          <Image
            src="/pizza.webp"
            className={styles.img_pizza}
            width={1300}
            height={715}
            alt="pizza"
          />
          <Image
            src="/refri.webp"
            className={styles.img_refri}
            width={340}
            height={710}
            alt="pizza"
          />
        </div>
        <h3>{JSON.stringify(counter)}</h3>
        <MessageButton />
      </main>
    </>
  );
}
